notARepository: 'quit'
git:
  overrideGpg: true
os:
  editPreset: nvim
gui:
  showBottomLine: false
  theme:
    activeBorderColor:
      - magenta
    selectedLineBgColor:
      - white
    selectedRangeBgColor:
      - pink
    unstagedChangesColor:
      - yellow
  border: rounded
  nerdFontsVersion: '3'
